
[System]
Simulate=0
AutoRemote=0
AutoDock=0
SECS Enable=1
Server IP=172.20.9.200
Server Port=12000
SystemType(1:ActiveEFEM,2:PassiveEFEM,3:Sorter)=3
DBAlarmlistUpdate=1
RFID_Bit=-1
FreeStyle=0
Language(0:Default, 1:zn_TW, 2:en_US, 3:zh_CN)=0
Equipment Name=Panel EFEM

[TRB1]
TCP_Type(0:None,1:Client,2:Server)=1
UpperArmFunction(0:NONE,1:NORMAL,2:I,3:FRAME)=1
LowerArmFunction(0:NONE,1:NORMAL,2:I,3:FRAME)=1
FrameTwoStepLoadArmBackPulse=10000
Xaxis_Disable=0
;Hardware Configuration
External_Xaxis_Disable=0
HardwareAllow Loadport(0:Disable,1:Enable)=11000000
HardwareAllow Aligner(0:Disable,1:Enable)=10
HardwareAllow Equipment(0:Disable,1:Enable)=1000
UseArmSameMovement=0
AlignerExchange=0
AngleBetweenOrgnAndXaxis=20000
UnldUseClmpCheckWaferTime(Enable > 0)=0
CheckRobotAir=0
MaintSpeed=6
RunSpeed=10

[TRB2]
TCP_Type(0:None,1:Client,2:Server)=1
UpperArmFunction(0:NONE,1:NORMAL,2:I,3:FRAME)=0
LowerArmFunction(0:NONE,1:NORMAL,2:I,3:FRAME)=0
FrameTwoStepLoadArmBackPulse=10000
Xaxis_Disable=1
HardwareAllow Loadport(0:Disable,1:Enable)=00000000
HardwareAllow Aligner(0:Disable,1:Enable)=00
HardwareAllow Equipment(0:Disable,1:Enable)=000
UseArmSameMovement=0
AlignerExchange=0
AngleBetweenOrgnAndXaxis=20000
UnldUseClmpCheckWaferTime(Enable > 0)=0
CheckRobotAir=0
MaintSpeed=6
RunSpeed=0

[TBL1]
TBL1 Type(RC560:0,RC550:1)=0
TCP_Type(0:None,1:Client,2:Server)=1

[TBL2]
TBL2 Type(RC560:0,RC550:1)=1
TCP_Type(0:None,1:Client,2:Server)=1

[TBL3]
TBL3 Type(RC560:0,RC550:1)=1
TCP_Type(0:None,1:Client,2:Server)=1

[TBL4]
TBL4 Type(RC560:0,RC550:1)=1
TCP_Type(0:None,1:Client,2:Server)=1

[TBL5]
TBL5 Type(RC560:0,RC550:1)=1
TCP_Type(0:None,1:Client,2:Server)=1

[TBL6]
TBL6 Type(RC560:0,RC550:1)=1
TCP_Type(0:None,1:Client,2:Server)=1

[STG1]
TCP_Type(0:None,1:Client,2:Server)=2
Mode(RV201,RB201,Other)=1
Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=5555555555555555
Adapter-Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=0000000000000000
Info-Pad Enable(0:disable,1:enable)=1111111111111111
Info-Pad Name=FUP1,FUP2,FUP3,FUP4,FUP5,FUP6,FUP7,FSB1,FSB2,FSB3,FSB4,FSB5,OCP1,OCP2,OCP3,FPO1
RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
Adapter-RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
SimulateGmap=10000000000000000001
BarcodeIndex=0
Mode(RV201,RB201,Other)=0

[STG2]
TCP_Type(0:None,1:Client,2:Server)=2
Mode(RV201,RB201,Other)=1
Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=5555555555555555
Adapter-Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=0000000000000000
Info-Pad Enable(0:disable,1:enable)=1111111111111111
Info-Pad Name=FUP1,FUP2,FUP3,FUP4,FUP5,FUP6,FUP7,FSB1,FSB2,FSB3,FSB4,FSB5,OCP1,OCP2,OCP3,FPO1
RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
Adapter-RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
SimulateGmap=10000000000000000001
BarcodeIndex=1
Mode(RV201,RB201,Other)=0

[STG3]
TCP_Type(0:None,1:Client,2:Server)=1
Mode(RV201,RB201,Other)=0
Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=1111111111111111
Adapter-Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=0000000000000000
Info-Pad Enable(0:disable,1:enable)=1111111111111111
Info-Pad Name=FUP1,FUP2,FUP3,FUP4,FUP5,FUP6,FUP7,FSB1,FSB2,FSB3,FSB4,FSB5,OCP1,OCP2,OCP3,FPO1
RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
Adapter-RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
SimulateGmap=0000000000000
BarcodeIndex=-1
Mode(RV201,RB201,Other)=0

[STG4]
TCP_Type(0:None,1:Client,2:Server)=1
Mode(RV201,RB201,Other)=0
Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=1111111111111111
Adapter-Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=0000000000000000
Info-Pad Enable(0:disable,1:enable)=1111111111111111
Info-Pad Name=FUP1,FUP2,FUP3,FUP4,FUP5,FUP6,FUP7,FSB1,FSB2,FSB3,FSB4,FSB5,OCP1,OCP2,OCP3,FPO1
RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
Adapter-RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
SimulateGmap=0000000000000
BarcodeIndex=-1
Mode(RV201,RB201,Other)=0

[STG5]
TCP_Type(0:None,1:Client,2:Server)=1
Mode(RV201,RB201,Other)=0
Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=1111111111111111
Adapter-Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=0000000000000000
Info-Pad Enable(0:disable,1:enable)=1111111111111111
Info-Pad Name=FUP1,FUP2,FUP3,FUP4,FUP5,FUP6,FUP7,FSB1,FSB2,FSB3,FSB4,FSB5,OCP1,OCP2,OCP3,FPO1
RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
Adapter-RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
SimulateGmap=0000000000000
BarcodeIndex=-1
Mode(RV201,RB201,Other)=0

[STG6]
TCP_Type(0:None,1:Client,2:Server)=1
Mode(RV201,RB201,Other)=0
Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=1111111111111111
Adapter-Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=0000000000000000
Info-Pad Enable(0:disable,1:enable)=1111111111111111
Info-Pad Name=FUP1,FUP2,FUP3,FUP4,FUP5,FUP6,FUP7,FSB1,FSB2,FSB3,FSB4,FSB5,OCP1,OCP2,OCP3,FPO1
RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
Adapter-RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
SimulateGmap=0000000000000
BarcodeIndex=-1
Mode(RV201,RB201,Other)=0

[STG7]
TCP_Type(0:None,1:Client,2:Server)=1
Mode(RV201,RB201,Other)=0
Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=1111111111111111
Adapter-Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=0000000000000000
Info-Pad Enable(0:disable,1:enable)=1111111111111111
Info-Pad Name=FUP1,FUP2,FUP3,FUP4,FUP5,FUP6,FUP7,FSB1,FSB2,FSB3,FSB4,FSB5,OCP1,OCP2,OCP3,FPO1
RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
Adapter-RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
SimulateGmap=0000000000000
BarcodeIndex=-1
Mode(RV201,RB201,Other)=0

[STG8]
TCP_Type(0:None,1:Client,2:Server)=1
Mode(RV201,RB201,Other)=0
Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=1111111111111111
Adapter-Info-Pad(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=0000000000000000
Info-Pad Enable(0:disable,1:enable)=1111111111111111
Info-Pad Name=FUP1,FUP2,FUP3,FUP4,FUP5,FUP6,FUP7,FSB1,FSB2,FSB3,FSB4,FSB5,OCP1,OCP2,OCP3,FPO1
RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
Adapter-RobotMapInfoEnable(0:disable,1:enable)=0000000000000000
SimulateGmap=0000000000000
BarcodeIndex=-1
Mode(RV201,RB201,Other)=0

[ALN1]
Mode(0:RA320,1:RA420,2:TurnTable,3:PanelXYR,4:TAL303)=4
UnClampLiftPinUp(0:false/1:true)=0
AngleBetweenNotchAndRbAFinger=0
AngleBetweenNotchAndRbBFinger=0
BarcodeIndex=-1

[ALN2]
Mode(0:RA320,1:RA420,2:TurnTable,3:PanelXYR,4:TAL303)=0
UnClampLiftPinUp(0:false/1:true)=0
AngleBetweenNotchAndRbAFinger=0
AngleBetweenNotchAndRbBFinger=0
BarcodeIndex=-1

[BUF1]
Type(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=0
PositionDetection=1
Slot1ExistBit=-1
Slot2ExistBit=-1
Slot3ExistBit=-1
Slot4ExistBit=-1
Around1Bit=-1
Around2Bit=-1
Around3Bit=-1
Around4Bit=-1

[BUF2]
Type(Unknow:0,Inch12:1,Inch08:2,Inch06:3,Frame:4,Panel:5)=0
PositionDetection=1
Slot1ExistBit=-1
Slot2ExistBit=-1
Slot3ExistBit=-1
Slot4ExistBit=-1
Around1Bit=-1
Around2Bit=-1
Around3Bit=-1
Around4Bit=-1

[DIO]
DIO0 Type(RC530:0,RC550:1)=1
DIO1 Type(RC530:0,RC550:1)=0
DIO2 Type(RC530:0,RC550:1)=0
DIO3 Type(RC530:0,RC550:1)=0
DIO4 Type(RC530:0,RC550:1)=0
DIO5 Type(RC530:0,RC550:1)=0

[FFU1]
Type(0:None,1:TOPWELL,2:AirTech)=2
FanCount=4
Comport=0
IP=172.20.9.191
Type(0:None,1:TOPWELL,2:AirTech,3:NicotraGebhardt)=0

[FFU2]
Type(0:None,1:TOPWELL,2:AirTech)=0
FanCount=1
Comport=0
IP=
Type(0:None,1:TOPWELL,2:AirTech,3:NicotraGebhardt)=0

[CMP1]
Camera(0:None,1:NPD)=1
IP=172.20.9.70

[CMP2]
Camera(0:None,1:NPD)=0
IP=

[BCR1]
Type(0:None,1:KeyenceSR2000,2:CognexDM370,3:KeyenceSR710)=3
Comport=5
IP=

[BCR2]
Type(0:None,1:KeyenceSR2000,2:CognexDM370,3:KeyenceSR710)=3
Comport=6
IP=

[BCR3]
Type(0:None,1:KeyenceSR2000,2:CognexDM370,3:KeyenceSR710)=0
Comport=0
IP=

[BCR4]
Type(0:None,1:KeyenceSR2000,2:CognexDM370,3:KeyenceSR710)=0
Comport=0
IP=

[BCR5]
Type(0:None,1:KeyenceSR2000,2:CognexDM370,3:KeyenceSR710)=0
Comport=0
IP=

[BCR6]
Type(0:None,1:KeyenceSR2000,2:CognexDM370,3:KeyenceSR710)=0
Comport=0
IP=

[BCR7]
Type(0:None,1:KeyenceSR2000,2:CognexDM370,3:KeyenceSR710)=0
Comport=0
IP=

[BCR8]
Type(0:None,1:KeyenceSR2000,2:CognexDM370,3:KeyenceSR710)=0
Comport=0
IP=

[RorzeUnit Disable]
TRB1 Disable=0
TRB2 Disable=1
TBL1 Disable=0
TBL2 Disable=1
TBL3 Disable=1
TBL4 Disable=1
TBL5 Disable=1
TBL6 Disable=1
STG1 Disable=1
STG2 Disable=1
STG3 Disable=1
STG4 Disable=1
STG5 Disable=1
STG6 Disable=1
STG7 Disable=1
STG8 Disable=1
ALN1 Disable=1
ALN2 Disable=1
OCR1 Disable=0
OCR2 Disable=0
OCR3 Disable=1
OCR4 Disable=1
DIO0 Disable=0
DIO1 Disable=0
DIO2 Disable=0
DIO3 Disable=0
DIO4 Disable=0
DIO5 Disable=1
BUF1 Enable Slot(0:disable,1)=0000
BUF2 Enable Slot(0:disable,1)=0000

[OCR Setting]
Recipe Number=30
LastFrontRecipe=1
LastBackRecipe=1
A1 Type(0:IS1740,1:WID120)=0
A2 Type(0:IS1740,1:WID120)=0
B1 Type(0:IS1740,1:WID120)=0
B2 Type(0:IS1740,1:WID120)=0
ReadOKGetImage=1
A1 Type(0:IS1740,1:WID120,2:TZ0031)=0
A2 Type(0:IS1740,1:WID120,2:TZ0031)=0
B1 Type(0:IS1740,1:WID120,2:TZ0031)=0
B2 Type(0:IS1740,1:WID120,2:TZ0031)=0

[Comport]
RFID Reader Maker 0:Unison/1:Heart/2:Omron/3:Brillian=1
RFID_1=3
RFID_2=4
RFID_3=0
RFID_4=0
RFID_5=0
RFID_6=0
RFID_7=0
RFID_8=0
FITC_1=0
FITC_2=0
FITC_3=0
FITC_4=0
FITC_5=0
FITC_6=0
FITC_7=0
FITC_8=0
EFEM FFU=0
Keyence_DL_RS1A=7

[E84 Disable]
E84_1_Disable=1
E84_2_Disable=1
E84_3_Disable=1
E84_4_Disable=1
E84_5_Disable=1
E84_6_Disable=1
E84_7_Disable=1
E84_8_Disable=1

[E84 TP TimeOut]
E84 Type(0:Remote IO,1:FITC)=0
TP1 TimeOut=2
TP2 TimeOut=2
TP3 TimeOut=60
TP4 TimeOut=60
TP5 TimeOut=2

[RorzeUnit IP Address]
Rorze Robot1=172.20.9.151
Rorze Robot2=172.20.9.152
Rorze TBL1=172.20.9.171
Rorze TBL2=172.20.9.172
Rorze TBL3=172.20.9.173
Rorze TBL4=172.20.9.174
Rorze TBL5=172.20.9.175
Rorze TBL6=172.20.9.176
Rorze Aligner_1=172.20.9.161
Rorze Aligner_2=172.20.9.162
Rorze Loadport_1=172.20.9.101
Rorze Loadport_2=172.20.9.102
Rorze Loadport_3=172.20.9.103
Rorze Loadport_4=172.20.9.104
Rorze Loadport_5=172.20.9.105
Rorze Loadport_6=172.20.9.106
Rorze Loadport_7=172.20.9.107
Rorze Loadport_8=172.20.9.108
OCR_A1=172.20.9.1
OCR_A2=172.20.9.2
OCR_B1=172.20.9.3
OCR_B2=172.20.9.4
Rorze DIO0=172.20.9.180
Rorze DIO1=172.20.9.181
Rorze DIO2=172.20.9.182
Rorze DIO3=172.20.9.183
Rorze DIO4=172.20.9.184
Rorze DIO5=172.20.9.185

[Gem IP Address]
GemIP1=127.0.0.1
Port=6000
GemIP2=127.0.0.1
ClientPort=5005

[RC550_0]
Driver4_FFU_Enable=0
HCL0_SB068A_Pressure_Enable=1
HCL0_SB068A_Pressure_Threshold(1pa~3pa)=0
FanSpeed=0
DVRAlarmn_Disable=0
PowerFan1Alarmn_Disable=0
PowerFan2Alarmn_Disable=0

[RC530_1]
CheckIO_Enable=0000000000000000
CheckIO_AorB=ABBBBBBBBAAAAAAA

[RC530_2]
CheckIO_Enable=0010000000000000
CheckIO_AorB=AABAAAAAAAAAAAAA

[RC530_3]
CheckIO_Enable=0000000000000000
CheckIO_AorB=AAAAAAAAAAAAAAAA

[RC530_4]
CheckIO_Enable=0000000000000000
CheckIO_AorB=AAAAAAAAAAAAAAAA

[Process]
;EQ手臂收回IO改成手臂伸出
EQ2IOSwitchToExtend=0

[CustomFunction]
RandomSelectWafer=1
AutoZoom=0
IdleLogOutTime(ms)=120000
OCRReadFailProcess(0:Continue,1:Abort,2:BackFoup,3:UserKeyIn)=0
FoupArrivalIdleTimeout(s)=-1
FoupWaitTransferTimeout(s)=-1
WaferIDFilterBit=10
OCRWarningsAutoRestTime(s)=10

[Notch Angle Adjustment Data]
AlignerA(RobotA to LoadPortA)=195800
AlignerA(RobotA to LoadPortB)=195800
AlignerA(RobotA to LoadPortC)=195800
AlignerA(RobotA to LoadPortD)=195800
AlignerA(RobotA to LoadPortE)=0
AlignerA(RobotA to LoadPortF)=0
AlignerA(RobotA to LoadPortG)=0
AlignerA(RobotA to LoadPortH)=0
AlignerA(RobotB to LoadPortA)=0
AlignerA(RobotB to LoadPortB)=0
AlignerA(RobotB to LoadPortC)=0
AlignerA(RobotB to LoadPortD)=0
AlignerA(RobotB to LoadPortE)=0
AlignerA(RobotB to LoadPortF)=0
AlignerA(RobotB to LoadPortG)=0
AlignerA(RobotB to LoadPortH)=0
RobotA to RobotB=0
AlignerB(RobotA to LoadPortA)=162944
AlignerB(RobotA to LoadPortB)=162944
AlignerB(RobotA to LoadPortC)=162944
AlignerB(RobotA to LoadPortD)=162944
AlignerB(RobotA to LoadPortE)=0
AlignerB(RobotA to LoadPortF)=0
AlignerB(RobotA to LoadPortG)=0
AlignerB(RobotA to LoadPortH)=0
AlignerB(RobotB to LoadPortA)=0
AlignerB(RobotB to LoadPortB)=0
AlignerB(RobotB to LoadPortC)=0
AlignerB(RobotB to LoadPortD)=0
AlignerB(RobotB to LoadPortE)=0
AlignerB(RobotB to LoadPortF)=0
AlignerB(RobotB to LoadPortG)=0
AlignerB(RobotB to LoadPortH)=0
RobotB to RobotA=0

[Signal Tower Color Setting(None, Red, RedBlinking, Yellow, YellowBlinking, Green, GreenBlinking, Blue, BlueBlinking)]
Error Occurring=2
Maintenance=1
Load UnLoad Request=0
Operator=0
Idle=6
Processing=5
Online Local=8
Online Remote=7
At Offline=0

[DataBase]
Sever=127.0.0.1
User=root
;PassWord=RORZE
PassWord=84149596
DBName=bwsdb-3200

[Adam1]
Disable=0
IP=192.168.0.6
Port=502

[Adam2]
Disable=0
IP=192.168.0.16
Port=502

[Equipment1]
Disable=0
Simulate=1
Name=Equipment1
TCP_Type(0:None,1:Client,2:Server)=0
IP=127.0.0.1
Port=5001
DefaultRecipe=
GetRecipeListEnable=
ProcessTimeout=60000

[Equipment2]
Disable=0
Simulate=1
Name=Equipment2
TCP_Type(0:None,1:Client,2:Server)=0
IP=127.0.0.1
Port=5002
DefaultRecipe=
GetRecipeListEnable=
ProcessTimeout=60000

[Equipment3]
Disable=0
Simulate=1
Name=Equipment3
TCP_Type(0:None,1:Client,2:Server)=0
IP=127.0.0.3
Port=5000
DefaultRecipe=
GetRecipeListEnable=
ProcessTimeout=60000

[Equipment4]
Disable=0
Simulate=1
Name=Equipment4
TCP_Type(0:None,1:Client,2:Server)=0
IP=127.0.0.1
Port=5003
DefaultRecipe=
GetRecipeListEnable=
ProcessTimeout=60000

[TurnTable String]
TurnTableA_angle_0=0
TurnTableA_angle_180=180000
TurnTableB_angle_0=0
TurnTableB_angle_180=180000

[Smart RFID]
Disable=0
ServerIP=172.20.9.200
Port=6100
RFID=172.20.9.210

[Safety IOStatus]
Disable=0
ServerIP=172.20.9.200
Port=12001
PLC=172.20.9.241

[Keyence MP]
Disable=0
IP=172.20.9.240
Port=502

[SIMCO]
Disable=1
IP=192.168.10.50
Port=10001

[IO_Signal_Information]
IsMaint=_DioBodyNo:1,_Bit:0,_NormalOff:0
LightCurtain1=_DioBodyNo:2,_Bit:2,_NormalOff:0

[GRPC]
BaseUrl=http://127.0.0.1:5000
GRPC_Disable=0
